Rework keygen
0chain/keygen pull request #5
Opened 2022-03-14 07:38 UTC by NaNuNaNu

Rework keygen according to issue: https://github.com/0chain/keygen/issues/4

2022-03-15 15:17 UTC, dabasov approved these changes
lgtm

2022-03-23 16:10 UTC, NaNuNaNu commented
@dabasov really not sure about the docker setup this will run with so would be good to have your input here.

2022-03-30 12:04 UTC, peterlimg requested changes

2022-03-30 12:04 UTC, peterlimg commented on go.mod
> +module github.com/0chain/keygen/code/go/0chain.net
Please update the module to `github.com/0chain/keygen`

2022-03-31 04:21 UTC, peterlimg approved these changes
lgtm

2022-03-31 04:22 UTC, merged